function out=DIV_etafunc_AMP_ver2(rho,normpdf_matrix,theta_plus_B,A,B,C,F,q,Z,mu)


out = ( ...
        C(:,1).*  (1-q)^2.*normpdf_matrix(:,1).*( B(:,1)./theta_plus_B(:,1) + (A(:,1)-rho)./theta_plus_B(:,1).*(F(:,1)./theta_plus_B(:,1)-mu)   ) +...
        C(:,2).*q*(1-q)  .*normpdf_matrix(:,2).*( B(:,2)./theta_plus_B(:,2) + (A(:,2)-rho)./theta_plus_B(:,2).*(F(:,2)./theta_plus_B(:,2)-mu)   ) +...
        C(:,3).*q*(1-q)  .*normpdf_matrix(:,3).*( B(:,3)./theta_plus_B(:,3) + (A(:,3)-rho)./theta_plus_B(:,3).*(F(:,3)./theta_plus_B(:,3)-mu)   ) +...
        C(:,4).*q^2      .*normpdf_matrix(:,4).*( B(:,4)./theta_plus_B(:,4) + (A(:,4)-rho)./theta_plus_B(:,4).*(F(:,4)./theta_plus_B(:,4)-mu)   )  ...
      )./Z;


end