function out= gammafunc_AMP_ver2(theta,normpdf_matrix,theta_plus_B,B,C,F,q,Z,mu)



out =  (...
         (1-q)^2  * C(:,1) .*( F(:,1).^2+ B(:,1).*theta.*theta_plus_B(:,1) )./theta_plus_B(:,1).^2 .*  normpdf_matrix(:,1)  +...
         q*(1-q)  * C(:,2) .*( F(:,2).^2+ B(:,2).*theta.*theta_plus_B(:,2) )./theta_plus_B(:,2).^2 .*  normpdf_matrix(:,2)  +...
         q*(1-q)  * C(:,3) .*( F(:,3).^2+ B(:,3).*theta.*theta_plus_B(:,3) )./theta_plus_B(:,3).^2 .*  normpdf_matrix(:,3)  +...
         q^2      * C(:,4) .*( F(:,4).^2+ B(:,4).*theta.*theta_plus_B(:,4) )./theta_plus_B(:,4).^2 .*  normpdf_matrix(:,4)...
       )./Z - mu.^2;
end


